// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/election.proto

package messages;

public final class Election {
  private Election() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ElectionInitiateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ElectionInitiate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NodeDetails initiator = 1;</code>
     * @return Whether the initiator field is set.
     */
    boolean hasInitiator();
    /**
     * <code>.NodeDetails initiator = 1;</code>
     * @return The initiator.
     */
    messages.Node.NodeDetails getInitiator();
    /**
     * <code>.NodeDetails initiator = 1;</code>
     */
    messages.Node.NodeDetailsOrBuilder getInitiatorOrBuilder();
  }
  /**
   * Protobuf type {@code ElectionInitiate}
   */
  public static final class ElectionInitiate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ElectionInitiate)
      ElectionInitiateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ElectionInitiate.newBuilder() to construct.
    private ElectionInitiate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ElectionInitiate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ElectionInitiate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ElectionInitiate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messages.Node.NodeDetails.Builder subBuilder = null;
              if (initiator_ != null) {
                subBuilder = initiator_.toBuilder();
              }
              initiator_ = input.readMessage(messages.Node.NodeDetails.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(initiator_);
                initiator_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Election.internal_static_ElectionInitiate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Election.internal_static_ElectionInitiate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Election.ElectionInitiate.class, messages.Election.ElectionInitiate.Builder.class);
    }

    public static final int INITIATOR_FIELD_NUMBER = 1;
    private messages.Node.NodeDetails initiator_;
    /**
     * <code>.NodeDetails initiator = 1;</code>
     * @return Whether the initiator field is set.
     */
    @java.lang.Override
    public boolean hasInitiator() {
      return initiator_ != null;
    }
    /**
     * <code>.NodeDetails initiator = 1;</code>
     * @return The initiator.
     */
    @java.lang.Override
    public messages.Node.NodeDetails getInitiator() {
      return initiator_ == null ? messages.Node.NodeDetails.getDefaultInstance() : initiator_;
    }
    /**
     * <code>.NodeDetails initiator = 1;</code>
     */
    @java.lang.Override
    public messages.Node.NodeDetailsOrBuilder getInitiatorOrBuilder() {
      return getInitiator();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (initiator_ != null) {
        output.writeMessage(1, getInitiator());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (initiator_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInitiator());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.Election.ElectionInitiate)) {
        return super.equals(obj);
      }
      messages.Election.ElectionInitiate other = (messages.Election.ElectionInitiate) obj;

      if (hasInitiator() != other.hasInitiator()) return false;
      if (hasInitiator()) {
        if (!getInitiator()
            .equals(other.getInitiator())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInitiator()) {
        hash = (37 * hash) + INITIATOR_FIELD_NUMBER;
        hash = (53 * hash) + getInitiator().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.Election.ElectionInitiate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Election.ElectionInitiate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Election.ElectionInitiate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Election.ElectionInitiate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.Election.ElectionInitiate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Election.ElectionInitiate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.Election.ElectionInitiate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ElectionInitiate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ElectionInitiate)
        messages.Election.ElectionInitiateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Election.internal_static_ElectionInitiate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Election.internal_static_ElectionInitiate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Election.ElectionInitiate.class, messages.Election.ElectionInitiate.Builder.class);
      }

      // Construct using messages.Election.ElectionInitiate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (initiatorBuilder_ == null) {
          initiator_ = null;
        } else {
          initiator_ = null;
          initiatorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Election.internal_static_ElectionInitiate_descriptor;
      }

      @java.lang.Override
      public messages.Election.ElectionInitiate getDefaultInstanceForType() {
        return messages.Election.ElectionInitiate.getDefaultInstance();
      }

      @java.lang.Override
      public messages.Election.ElectionInitiate build() {
        messages.Election.ElectionInitiate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.Election.ElectionInitiate buildPartial() {
        messages.Election.ElectionInitiate result = new messages.Election.ElectionInitiate(this);
        if (initiatorBuilder_ == null) {
          result.initiator_ = initiator_;
        } else {
          result.initiator_ = initiatorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Election.ElectionInitiate) {
          return mergeFrom((messages.Election.ElectionInitiate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Election.ElectionInitiate other) {
        if (other == messages.Election.ElectionInitiate.getDefaultInstance()) return this;
        if (other.hasInitiator()) {
          mergeInitiator(other.getInitiator());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Election.ElectionInitiate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Election.ElectionInitiate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private messages.Node.NodeDetails initiator_;
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> initiatorBuilder_;
      /**
       * <code>.NodeDetails initiator = 1;</code>
       * @return Whether the initiator field is set.
       */
      public boolean hasInitiator() {
        return initiatorBuilder_ != null || initiator_ != null;
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       * @return The initiator.
       */
      public messages.Node.NodeDetails getInitiator() {
        if (initiatorBuilder_ == null) {
          return initiator_ == null ? messages.Node.NodeDetails.getDefaultInstance() : initiator_;
        } else {
          return initiatorBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      public Builder setInitiator(messages.Node.NodeDetails value) {
        if (initiatorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initiator_ = value;
          onChanged();
        } else {
          initiatorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      public Builder setInitiator(
          messages.Node.NodeDetails.Builder builderForValue) {
        if (initiatorBuilder_ == null) {
          initiator_ = builderForValue.build();
          onChanged();
        } else {
          initiatorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      public Builder mergeInitiator(messages.Node.NodeDetails value) {
        if (initiatorBuilder_ == null) {
          if (initiator_ != null) {
            initiator_ =
              messages.Node.NodeDetails.newBuilder(initiator_).mergeFrom(value).buildPartial();
          } else {
            initiator_ = value;
          }
          onChanged();
        } else {
          initiatorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      public Builder clearInitiator() {
        if (initiatorBuilder_ == null) {
          initiator_ = null;
          onChanged();
        } else {
          initiator_ = null;
          initiatorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      public messages.Node.NodeDetails.Builder getInitiatorBuilder() {
        
        onChanged();
        return getInitiatorFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      public messages.Node.NodeDetailsOrBuilder getInitiatorOrBuilder() {
        if (initiatorBuilder_ != null) {
          return initiatorBuilder_.getMessageOrBuilder();
        } else {
          return initiator_ == null ?
              messages.Node.NodeDetails.getDefaultInstance() : initiator_;
        }
      }
      /**
       * <code>.NodeDetails initiator = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> 
          getInitiatorFieldBuilder() {
        if (initiatorBuilder_ == null) {
          initiatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder>(
                  getInitiator(),
                  getParentForChildren(),
                  isClean());
          initiator_ = null;
        }
        return initiatorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ElectionInitiate)
    }

    // @@protoc_insertion_point(class_scope:ElectionInitiate)
    private static final messages.Election.ElectionInitiate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.Election.ElectionInitiate();
    }

    public static messages.Election.ElectionInitiate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ElectionInitiate>
        PARSER = new com.google.protobuf.AbstractParser<ElectionInitiate>() {
      @java.lang.Override
      public ElectionInitiate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ElectionInitiate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ElectionInitiate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ElectionInitiate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.Election.ElectionInitiate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VictoryMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VictoryMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return Whether the leader field is set.
     */
    boolean hasLeader();
    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return The leader.
     */
    messages.Node.NodeDetails getLeader();
    /**
     * <code>.NodeDetails leader = 1;</code>
     */
    messages.Node.NodeDetailsOrBuilder getLeaderOrBuilder();
  }
  /**
   * Protobuf type {@code VictoryMessage}
   */
  public static final class VictoryMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VictoryMessage)
      VictoryMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VictoryMessage.newBuilder() to construct.
    private VictoryMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VictoryMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VictoryMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VictoryMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messages.Node.NodeDetails.Builder subBuilder = null;
              if (leader_ != null) {
                subBuilder = leader_.toBuilder();
              }
              leader_ = input.readMessage(messages.Node.NodeDetails.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(leader_);
                leader_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Election.internal_static_VictoryMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Election.internal_static_VictoryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Election.VictoryMessage.class, messages.Election.VictoryMessage.Builder.class);
    }

    public static final int LEADER_FIELD_NUMBER = 1;
    private messages.Node.NodeDetails leader_;
    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return Whether the leader field is set.
     */
    @java.lang.Override
    public boolean hasLeader() {
      return leader_ != null;
    }
    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return The leader.
     */
    @java.lang.Override
    public messages.Node.NodeDetails getLeader() {
      return leader_ == null ? messages.Node.NodeDetails.getDefaultInstance() : leader_;
    }
    /**
     * <code>.NodeDetails leader = 1;</code>
     */
    @java.lang.Override
    public messages.Node.NodeDetailsOrBuilder getLeaderOrBuilder() {
      return getLeader();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (leader_ != null) {
        output.writeMessage(1, getLeader());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (leader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLeader());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.Election.VictoryMessage)) {
        return super.equals(obj);
      }
      messages.Election.VictoryMessage other = (messages.Election.VictoryMessage) obj;

      if (hasLeader() != other.hasLeader()) return false;
      if (hasLeader()) {
        if (!getLeader()
            .equals(other.getLeader())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLeader()) {
        hash = (37 * hash) + LEADER_FIELD_NUMBER;
        hash = (53 * hash) + getLeader().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.Election.VictoryMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Election.VictoryMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Election.VictoryMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Election.VictoryMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Election.VictoryMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Election.VictoryMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Election.VictoryMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Election.VictoryMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Election.VictoryMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.Election.VictoryMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Election.VictoryMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Election.VictoryMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.Election.VictoryMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VictoryMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VictoryMessage)
        messages.Election.VictoryMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Election.internal_static_VictoryMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Election.internal_static_VictoryMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Election.VictoryMessage.class, messages.Election.VictoryMessage.Builder.class);
      }

      // Construct using messages.Election.VictoryMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (leaderBuilder_ == null) {
          leader_ = null;
        } else {
          leader_ = null;
          leaderBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Election.internal_static_VictoryMessage_descriptor;
      }

      @java.lang.Override
      public messages.Election.VictoryMessage getDefaultInstanceForType() {
        return messages.Election.VictoryMessage.getDefaultInstance();
      }

      @java.lang.Override
      public messages.Election.VictoryMessage build() {
        messages.Election.VictoryMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.Election.VictoryMessage buildPartial() {
        messages.Election.VictoryMessage result = new messages.Election.VictoryMessage(this);
        if (leaderBuilder_ == null) {
          result.leader_ = leader_;
        } else {
          result.leader_ = leaderBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Election.VictoryMessage) {
          return mergeFrom((messages.Election.VictoryMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Election.VictoryMessage other) {
        if (other == messages.Election.VictoryMessage.getDefaultInstance()) return this;
        if (other.hasLeader()) {
          mergeLeader(other.getLeader());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Election.VictoryMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Election.VictoryMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private messages.Node.NodeDetails leader_;
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> leaderBuilder_;
      /**
       * <code>.NodeDetails leader = 1;</code>
       * @return Whether the leader field is set.
       */
      public boolean hasLeader() {
        return leaderBuilder_ != null || leader_ != null;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       * @return The leader.
       */
      public messages.Node.NodeDetails getLeader() {
        if (leaderBuilder_ == null) {
          return leader_ == null ? messages.Node.NodeDetails.getDefaultInstance() : leader_;
        } else {
          return leaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder setLeader(messages.Node.NodeDetails value) {
        if (leaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leader_ = value;
          onChanged();
        } else {
          leaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder setLeader(
          messages.Node.NodeDetails.Builder builderForValue) {
        if (leaderBuilder_ == null) {
          leader_ = builderForValue.build();
          onChanged();
        } else {
          leaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder mergeLeader(messages.Node.NodeDetails value) {
        if (leaderBuilder_ == null) {
          if (leader_ != null) {
            leader_ =
              messages.Node.NodeDetails.newBuilder(leader_).mergeFrom(value).buildPartial();
          } else {
            leader_ = value;
          }
          onChanged();
        } else {
          leaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder clearLeader() {
        if (leaderBuilder_ == null) {
          leader_ = null;
          onChanged();
        } else {
          leader_ = null;
          leaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public messages.Node.NodeDetails.Builder getLeaderBuilder() {
        
        onChanged();
        return getLeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public messages.Node.NodeDetailsOrBuilder getLeaderOrBuilder() {
        if (leaderBuilder_ != null) {
          return leaderBuilder_.getMessageOrBuilder();
        } else {
          return leader_ == null ?
              messages.Node.NodeDetails.getDefaultInstance() : leader_;
        }
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> 
          getLeaderFieldBuilder() {
        if (leaderBuilder_ == null) {
          leaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder>(
                  getLeader(),
                  getParentForChildren(),
                  isClean());
          leader_ = null;
        }
        return leaderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VictoryMessage)
    }

    // @@protoc_insertion_point(class_scope:VictoryMessage)
    private static final messages.Election.VictoryMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.Election.VictoryMessage();
    }

    public static messages.Election.VictoryMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VictoryMessage>
        PARSER = new com.google.protobuf.AbstractParser<VictoryMessage>() {
      @java.lang.Override
      public VictoryMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VictoryMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VictoryMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VictoryMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.Election.VictoryMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElectionInitiate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ElectionInitiate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VictoryMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VictoryMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protos/election.proto\032\021protos/node.pro" +
      "to\"3\n\020ElectionInitiate\022\037\n\tinitiator\030\001 \001(" +
      "\0132\014.NodeDetails\".\n\016VictoryMessage\022\034\n\006lea" +
      "der\030\001 \001(\0132\014.NodeDetailsB\024\n\010messagesB\010Ele" +
      "ctionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.Node.getDescriptor(),
        });
    internal_static_ElectionInitiate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ElectionInitiate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ElectionInitiate_descriptor,
        new java.lang.String[] { "Initiator", });
    internal_static_VictoryMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VictoryMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VictoryMessage_descriptor,
        new java.lang.String[] { "Leader", });
    messages.Node.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
