// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/leader.proto

package messages;

public final class Leader {
  private Leader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LeaderDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return Whether the leader field is set.
     */
    boolean hasLeader();
    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return The leader.
     */
    messages.Node.NodeDetails getLeader();
    /**
     * <code>.NodeDetails leader = 1;</code>
     */
    messages.Node.NodeDetailsOrBuilder getLeaderOrBuilder();
  }
  /**
   * Protobuf type {@code LeaderDetails}
   */
  public static final class LeaderDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LeaderDetails)
      LeaderDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LeaderDetails.newBuilder() to construct.
    private LeaderDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LeaderDetails() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LeaderDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messages.Node.NodeDetails.Builder subBuilder = null;
              if (leader_ != null) {
                subBuilder = leader_.toBuilder();
              }
              leader_ = input.readMessage(messages.Node.NodeDetails.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(leader_);
                leader_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Leader.internal_static_LeaderDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Leader.internal_static_LeaderDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Leader.LeaderDetails.class, messages.Leader.LeaderDetails.Builder.class);
    }

    public static final int LEADER_FIELD_NUMBER = 1;
    private messages.Node.NodeDetails leader_;
    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return Whether the leader field is set.
     */
    @java.lang.Override
    public boolean hasLeader() {
      return leader_ != null;
    }
    /**
     * <code>.NodeDetails leader = 1;</code>
     * @return The leader.
     */
    @java.lang.Override
    public messages.Node.NodeDetails getLeader() {
      return leader_ == null ? messages.Node.NodeDetails.getDefaultInstance() : leader_;
    }
    /**
     * <code>.NodeDetails leader = 1;</code>
     */
    @java.lang.Override
    public messages.Node.NodeDetailsOrBuilder getLeaderOrBuilder() {
      return getLeader();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (leader_ != null) {
        output.writeMessage(1, getLeader());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (leader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLeader());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.Leader.LeaderDetails)) {
        return super.equals(obj);
      }
      messages.Leader.LeaderDetails other = (messages.Leader.LeaderDetails) obj;

      if (hasLeader() != other.hasLeader()) return false;
      if (hasLeader()) {
        if (!getLeader()
            .equals(other.getLeader())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLeader()) {
        hash = (37 * hash) + LEADER_FIELD_NUMBER;
        hash = (53 * hash) + getLeader().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.Leader.LeaderDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Leader.LeaderDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Leader.LeaderDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Leader.LeaderDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.Leader.LeaderDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Leader.LeaderDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.Leader.LeaderDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LeaderDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderDetails)
        messages.Leader.LeaderDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Leader.internal_static_LeaderDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Leader.internal_static_LeaderDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Leader.LeaderDetails.class, messages.Leader.LeaderDetails.Builder.class);
      }

      // Construct using messages.Leader.LeaderDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (leaderBuilder_ == null) {
          leader_ = null;
        } else {
          leader_ = null;
          leaderBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Leader.internal_static_LeaderDetails_descriptor;
      }

      @java.lang.Override
      public messages.Leader.LeaderDetails getDefaultInstanceForType() {
        return messages.Leader.LeaderDetails.getDefaultInstance();
      }

      @java.lang.Override
      public messages.Leader.LeaderDetails build() {
        messages.Leader.LeaderDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.Leader.LeaderDetails buildPartial() {
        messages.Leader.LeaderDetails result = new messages.Leader.LeaderDetails(this);
        if (leaderBuilder_ == null) {
          result.leader_ = leader_;
        } else {
          result.leader_ = leaderBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Leader.LeaderDetails) {
          return mergeFrom((messages.Leader.LeaderDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Leader.LeaderDetails other) {
        if (other == messages.Leader.LeaderDetails.getDefaultInstance()) return this;
        if (other.hasLeader()) {
          mergeLeader(other.getLeader());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Leader.LeaderDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Leader.LeaderDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private messages.Node.NodeDetails leader_;
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> leaderBuilder_;
      /**
       * <code>.NodeDetails leader = 1;</code>
       * @return Whether the leader field is set.
       */
      public boolean hasLeader() {
        return leaderBuilder_ != null || leader_ != null;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       * @return The leader.
       */
      public messages.Node.NodeDetails getLeader() {
        if (leaderBuilder_ == null) {
          return leader_ == null ? messages.Node.NodeDetails.getDefaultInstance() : leader_;
        } else {
          return leaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder setLeader(messages.Node.NodeDetails value) {
        if (leaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leader_ = value;
          onChanged();
        } else {
          leaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder setLeader(
          messages.Node.NodeDetails.Builder builderForValue) {
        if (leaderBuilder_ == null) {
          leader_ = builderForValue.build();
          onChanged();
        } else {
          leaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder mergeLeader(messages.Node.NodeDetails value) {
        if (leaderBuilder_ == null) {
          if (leader_ != null) {
            leader_ =
              messages.Node.NodeDetails.newBuilder(leader_).mergeFrom(value).buildPartial();
          } else {
            leader_ = value;
          }
          onChanged();
        } else {
          leaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public Builder clearLeader() {
        if (leaderBuilder_ == null) {
          leader_ = null;
          onChanged();
        } else {
          leader_ = null;
          leaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public messages.Node.NodeDetails.Builder getLeaderBuilder() {
        
        onChanged();
        return getLeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      public messages.Node.NodeDetailsOrBuilder getLeaderOrBuilder() {
        if (leaderBuilder_ != null) {
          return leaderBuilder_.getMessageOrBuilder();
        } else {
          return leader_ == null ?
              messages.Node.NodeDetails.getDefaultInstance() : leader_;
        }
      }
      /**
       * <code>.NodeDetails leader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> 
          getLeaderFieldBuilder() {
        if (leaderBuilder_ == null) {
          leaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder>(
                  getLeader(),
                  getParentForChildren(),
                  isClean());
          leader_ = null;
        }
        return leaderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LeaderDetails)
    }

    // @@protoc_insertion_point(class_scope:LeaderDetails)
    private static final messages.Leader.LeaderDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.Leader.LeaderDetails();
    }

    public static messages.Leader.LeaderDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LeaderDetails>
        PARSER = new com.google.protobuf.AbstractParser<LeaderDetails>() {
      @java.lang.Override
      public LeaderDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LeaderDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaderDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.Leader.LeaderDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protos/leader.proto\032\021protos/node.proto" +
      "\"-\n\rLeaderDetails\022\034\n\006leader\030\001 \001(\0132\014.Node" +
      "DetailsB\022\n\010messagesB\006Leaderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.Node.getDescriptor(),
        });
    internal_static_LeaderDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LeaderDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderDetails_descriptor,
        new java.lang.String[] { "Leader", });
    messages.Node.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
