// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/replicate.proto

package messages;

public final class Replicate {
  private Replicate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReplicateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReplicateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MessageDetails details = 1;</code>
     * @return Whether the details field is set.
     */
    boolean hasDetails();
    /**
     * <code>.MessageDetails details = 1;</code>
     * @return The details.
     */
    messages.Message.MessageDetails getDetails();
    /**
     * <code>.MessageDetails details = 1;</code>
     */
    messages.Message.MessageDetailsOrBuilder getDetailsOrBuilder();
  }
  /**
   * Protobuf type {@code ReplicateMessage}
   */
  public static final class ReplicateMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReplicateMessage)
      ReplicateMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReplicateMessage.newBuilder() to construct.
    private ReplicateMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReplicateMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReplicateMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReplicateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messages.Message.MessageDetails.Builder subBuilder = null;
              if (details_ != null) {
                subBuilder = details_.toBuilder();
              }
              details_ = input.readMessage(messages.Message.MessageDetails.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(details_);
                details_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Replicate.internal_static_ReplicateMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Replicate.internal_static_ReplicateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Replicate.ReplicateMessage.class, messages.Replicate.ReplicateMessage.Builder.class);
    }

    public static final int DETAILS_FIELD_NUMBER = 1;
    private messages.Message.MessageDetails details_;
    /**
     * <code>.MessageDetails details = 1;</code>
     * @return Whether the details field is set.
     */
    @java.lang.Override
    public boolean hasDetails() {
      return details_ != null;
    }
    /**
     * <code>.MessageDetails details = 1;</code>
     * @return The details.
     */
    @java.lang.Override
    public messages.Message.MessageDetails getDetails() {
      return details_ == null ? messages.Message.MessageDetails.getDefaultInstance() : details_;
    }
    /**
     * <code>.MessageDetails details = 1;</code>
     */
    @java.lang.Override
    public messages.Message.MessageDetailsOrBuilder getDetailsOrBuilder() {
      return getDetails();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (details_ != null) {
        output.writeMessage(1, getDetails());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (details_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDetails());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.Replicate.ReplicateMessage)) {
        return super.equals(obj);
      }
      messages.Replicate.ReplicateMessage other = (messages.Replicate.ReplicateMessage) obj;

      if (hasDetails() != other.hasDetails()) return false;
      if (hasDetails()) {
        if (!getDetails()
            .equals(other.getDetails())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDetails()) {
        hash = (37 * hash) + DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getDetails().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.Replicate.ReplicateMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Replicate.ReplicateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.Replicate.ReplicateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Replicate.ReplicateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.Replicate.ReplicateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReplicateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReplicateMessage)
        messages.Replicate.ReplicateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Replicate.internal_static_ReplicateMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Replicate.internal_static_ReplicateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Replicate.ReplicateMessage.class, messages.Replicate.ReplicateMessage.Builder.class);
      }

      // Construct using messages.Replicate.ReplicateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (detailsBuilder_ == null) {
          details_ = null;
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Replicate.internal_static_ReplicateMessage_descriptor;
      }

      @java.lang.Override
      public messages.Replicate.ReplicateMessage getDefaultInstanceForType() {
        return messages.Replicate.ReplicateMessage.getDefaultInstance();
      }

      @java.lang.Override
      public messages.Replicate.ReplicateMessage build() {
        messages.Replicate.ReplicateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.Replicate.ReplicateMessage buildPartial() {
        messages.Replicate.ReplicateMessage result = new messages.Replicate.ReplicateMessage(this);
        if (detailsBuilder_ == null) {
          result.details_ = details_;
        } else {
          result.details_ = detailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Replicate.ReplicateMessage) {
          return mergeFrom((messages.Replicate.ReplicateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Replicate.ReplicateMessage other) {
        if (other == messages.Replicate.ReplicateMessage.getDefaultInstance()) return this;
        if (other.hasDetails()) {
          mergeDetails(other.getDetails());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Replicate.ReplicateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Replicate.ReplicateMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private messages.Message.MessageDetails details_;
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Message.MessageDetails, messages.Message.MessageDetails.Builder, messages.Message.MessageDetailsOrBuilder> detailsBuilder_;
      /**
       * <code>.MessageDetails details = 1;</code>
       * @return Whether the details field is set.
       */
      public boolean hasDetails() {
        return detailsBuilder_ != null || details_ != null;
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       * @return The details.
       */
      public messages.Message.MessageDetails getDetails() {
        if (detailsBuilder_ == null) {
          return details_ == null ? messages.Message.MessageDetails.getDefaultInstance() : details_;
        } else {
          return detailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      public Builder setDetails(messages.Message.MessageDetails value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          details_ = value;
          onChanged();
        } else {
          detailsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      public Builder setDetails(
          messages.Message.MessageDetails.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          details_ = builderForValue.build();
          onChanged();
        } else {
          detailsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      public Builder mergeDetails(messages.Message.MessageDetails value) {
        if (detailsBuilder_ == null) {
          if (details_ != null) {
            details_ =
              messages.Message.MessageDetails.newBuilder(details_).mergeFrom(value).buildPartial();
          } else {
            details_ = value;
          }
          onChanged();
        } else {
          detailsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      public Builder clearDetails() {
        if (detailsBuilder_ == null) {
          details_ = null;
          onChanged();
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      public messages.Message.MessageDetails.Builder getDetailsBuilder() {
        
        onChanged();
        return getDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      public messages.Message.MessageDetailsOrBuilder getDetailsOrBuilder() {
        if (detailsBuilder_ != null) {
          return detailsBuilder_.getMessageOrBuilder();
        } else {
          return details_ == null ?
              messages.Message.MessageDetails.getDefaultInstance() : details_;
        }
      }
      /**
       * <code>.MessageDetails details = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Message.MessageDetails, messages.Message.MessageDetails.Builder, messages.Message.MessageDetailsOrBuilder> 
          getDetailsFieldBuilder() {
        if (detailsBuilder_ == null) {
          detailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              messages.Message.MessageDetails, messages.Message.MessageDetails.Builder, messages.Message.MessageDetailsOrBuilder>(
                  getDetails(),
                  getParentForChildren(),
                  isClean());
          details_ = null;
        }
        return detailsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReplicateMessage)
    }

    // @@protoc_insertion_point(class_scope:ReplicateMessage)
    private static final messages.Replicate.ReplicateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.Replicate.ReplicateMessage();
    }

    public static messages.Replicate.ReplicateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReplicateMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReplicateMessage>() {
      @java.lang.Override
      public ReplicateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReplicateMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReplicateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReplicateMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.Replicate.ReplicateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReplicateMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReplicateMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protos/replicate.proto\032\024protos/message" +
      ".proto\"4\n\020ReplicateMessage\022 \n\007details\030\001 " +
      "\001(\0132\017.MessageDetailsB\025\n\010messagesB\tReplic" +
      "ateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.Message.getDescriptor(),
        });
    internal_static_ReplicateMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReplicateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReplicateMessage_descriptor,
        new java.lang.String[] { "Details", });
    messages.Message.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
