// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/synch.proto

package messages;

public final class Synchronization {
  private Synchronization() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NodeDetails node = 1;</code>
     * @return Whether the node field is set.
     */
    boolean hasNode();
    /**
     * <code>.NodeDetails node = 1;</code>
     * @return The node.
     */
    messages.Node.NodeDetails getNode();
    /**
     * <code>.NodeDetails node = 1;</code>
     */
    messages.Node.NodeDetailsOrBuilder getNodeOrBuilder();
  }
  /**
   * Protobuf type {@code SyncRequest}
   */
  public static final class SyncRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SyncRequest)
      SyncRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncRequest.newBuilder() to construct.
    private SyncRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SyncRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messages.Node.NodeDetails.Builder subBuilder = null;
              if (node_ != null) {
                subBuilder = node_.toBuilder();
              }
              node_ = input.readMessage(messages.Node.NodeDetails.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(node_);
                node_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Synchronization.internal_static_SyncRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Synchronization.internal_static_SyncRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Synchronization.SyncRequest.class, messages.Synchronization.SyncRequest.Builder.class);
    }

    public static final int NODE_FIELD_NUMBER = 1;
    private messages.Node.NodeDetails node_;
    /**
     * <code>.NodeDetails node = 1;</code>
     * @return Whether the node field is set.
     */
    @java.lang.Override
    public boolean hasNode() {
      return node_ != null;
    }
    /**
     * <code>.NodeDetails node = 1;</code>
     * @return The node.
     */
    @java.lang.Override
    public messages.Node.NodeDetails getNode() {
      return node_ == null ? messages.Node.NodeDetails.getDefaultInstance() : node_;
    }
    /**
     * <code>.NodeDetails node = 1;</code>
     */
    @java.lang.Override
    public messages.Node.NodeDetailsOrBuilder getNodeOrBuilder() {
      return getNode();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (node_ != null) {
        output.writeMessage(1, getNode());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (node_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNode());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.Synchronization.SyncRequest)) {
        return super.equals(obj);
      }
      messages.Synchronization.SyncRequest other = (messages.Synchronization.SyncRequest) obj;

      if (hasNode() != other.hasNode()) return false;
      if (hasNode()) {
        if (!getNode()
            .equals(other.getNode())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNode()) {
        hash = (37 * hash) + NODE_FIELD_NUMBER;
        hash = (53 * hash) + getNode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.Synchronization.SyncRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Synchronization.SyncRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Synchronization.SyncRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Synchronization.SyncRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.Synchronization.SyncRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Synchronization.SyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.Synchronization.SyncRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SyncRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncRequest)
        messages.Synchronization.SyncRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Synchronization.internal_static_SyncRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Synchronization.internal_static_SyncRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Synchronization.SyncRequest.class, messages.Synchronization.SyncRequest.Builder.class);
      }

      // Construct using messages.Synchronization.SyncRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodeBuilder_ == null) {
          node_ = null;
        } else {
          node_ = null;
          nodeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Synchronization.internal_static_SyncRequest_descriptor;
      }

      @java.lang.Override
      public messages.Synchronization.SyncRequest getDefaultInstanceForType() {
        return messages.Synchronization.SyncRequest.getDefaultInstance();
      }

      @java.lang.Override
      public messages.Synchronization.SyncRequest build() {
        messages.Synchronization.SyncRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.Synchronization.SyncRequest buildPartial() {
        messages.Synchronization.SyncRequest result = new messages.Synchronization.SyncRequest(this);
        if (nodeBuilder_ == null) {
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Synchronization.SyncRequest) {
          return mergeFrom((messages.Synchronization.SyncRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Synchronization.SyncRequest other) {
        if (other == messages.Synchronization.SyncRequest.getDefaultInstance()) return this;
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Synchronization.SyncRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Synchronization.SyncRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private messages.Node.NodeDetails node_;
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> nodeBuilder_;
      /**
       * <code>.NodeDetails node = 1;</code>
       * @return Whether the node field is set.
       */
      public boolean hasNode() {
        return nodeBuilder_ != null || node_ != null;
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       * @return The node.
       */
      public messages.Node.NodeDetails getNode() {
        if (nodeBuilder_ == null) {
          return node_ == null ? messages.Node.NodeDetails.getDefaultInstance() : node_;
        } else {
          return nodeBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      public Builder setNode(messages.Node.NodeDetails value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          nodeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      public Builder setNode(
          messages.Node.NodeDetails.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          nodeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      public Builder mergeNode(messages.Node.NodeDetails value) {
        if (nodeBuilder_ == null) {
          if (node_ != null) {
            node_ =
              messages.Node.NodeDetails.newBuilder(node_).mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          nodeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = null;
          onChanged();
        } else {
          node_ = null;
          nodeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      public messages.Node.NodeDetails.Builder getNodeBuilder() {
        
        onChanged();
        return getNodeFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      public messages.Node.NodeDetailsOrBuilder getNodeOrBuilder() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilder();
        } else {
          return node_ == null ?
              messages.Node.NodeDetails.getDefaultInstance() : node_;
        }
      }
      /**
       * <code>.NodeDetails node = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder> 
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              messages.Node.NodeDetails, messages.Node.NodeDetails.Builder, messages.Node.NodeDetailsOrBuilder>(
                  getNode(),
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SyncRequest)
    }

    // @@protoc_insertion_point(class_scope:SyncRequest)
    private static final messages.Synchronization.SyncRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.Synchronization.SyncRequest();
    }

    public static messages.Synchronization.SyncRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncRequest>
        PARSER = new com.google.protobuf.AbstractParser<SyncRequest>() {
      @java.lang.Override
      public SyncRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.Synchronization.SyncRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SnapshotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Snapshot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */
    int getCurrentOffsetsCount();
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */
    boolean containsCurrentOffsets(
        java.lang.String key);
    /**
     * Use {@link #getCurrentOffsetsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Long>
    getCurrentOffsets();
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Long>
    getCurrentOffsetsMap();
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */

    long getCurrentOffsetsOrDefault(
        java.lang.String key,
        long defaultValue);
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */

    long getCurrentOffsetsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Snapshot}
   */
  public static final class Snapshot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Snapshot)
      SnapshotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Snapshot.newBuilder() to construct.
    private Snapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Snapshot() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Snapshot();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Snapshot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                currentOffsets_ = com.google.protobuf.MapField.newMapField(
                    CurrentOffsetsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              currentOffsets__ = input.readMessage(
                  CurrentOffsetsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              currentOffsets_.getMutableMap().put(
                  currentOffsets__.getKey(), currentOffsets__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Synchronization.internal_static_Snapshot_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetCurrentOffsets();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Synchronization.internal_static_Snapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Synchronization.Snapshot.class, messages.Synchronization.Snapshot.Builder.class);
    }

    public static final int CURRENTOFFSETS_FIELD_NUMBER = 1;
    private static final class CurrentOffsetsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Long>newDefaultInstance(
                  messages.Synchronization.internal_static_Snapshot_CurrentOffsetsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.UINT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> currentOffsets_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetCurrentOffsets() {
      if (currentOffsets_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CurrentOffsetsDefaultEntryHolder.defaultEntry);
      }
      return currentOffsets_;
    }

    public int getCurrentOffsetsCount() {
      return internalGetCurrentOffsets().getMap().size();
    }
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */

    @java.lang.Override
    public boolean containsCurrentOffsets(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCurrentOffsets().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCurrentOffsetsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getCurrentOffsets() {
      return getCurrentOffsetsMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Long> getCurrentOffsetsMap() {
      return internalGetCurrentOffsets().getMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */
    @java.lang.Override

    public long getCurrentOffsetsOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetCurrentOffsets().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
     */
    @java.lang.Override

    public long getCurrentOffsetsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetCurrentOffsets().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCurrentOffsets(),
          CurrentOffsetsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
           : internalGetCurrentOffsets().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
        currentOffsets__ = CurrentOffsetsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, currentOffsets__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.Synchronization.Snapshot)) {
        return super.equals(obj);
      }
      messages.Synchronization.Snapshot other = (messages.Synchronization.Snapshot) obj;

      if (!internalGetCurrentOffsets().equals(
          other.internalGetCurrentOffsets())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetCurrentOffsets().getMap().isEmpty()) {
        hash = (37 * hash) + CURRENTOFFSETS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCurrentOffsets().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.Synchronization.Snapshot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Synchronization.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Synchronization.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Synchronization.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.Synchronization.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.Synchronization.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.Synchronization.Snapshot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Snapshot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Snapshot)
        messages.Synchronization.SnapshotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Synchronization.internal_static_Snapshot_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetCurrentOffsets();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableCurrentOffsets();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Synchronization.internal_static_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Synchronization.Snapshot.class, messages.Synchronization.Snapshot.Builder.class);
      }

      // Construct using messages.Synchronization.Snapshot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableCurrentOffsets().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Synchronization.internal_static_Snapshot_descriptor;
      }

      @java.lang.Override
      public messages.Synchronization.Snapshot getDefaultInstanceForType() {
        return messages.Synchronization.Snapshot.getDefaultInstance();
      }

      @java.lang.Override
      public messages.Synchronization.Snapshot build() {
        messages.Synchronization.Snapshot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.Synchronization.Snapshot buildPartial() {
        messages.Synchronization.Snapshot result = new messages.Synchronization.Snapshot(this);
        int from_bitField0_ = bitField0_;
        result.currentOffsets_ = internalGetCurrentOffsets();
        result.currentOffsets_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Synchronization.Snapshot) {
          return mergeFrom((messages.Synchronization.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Synchronization.Snapshot other) {
        if (other == messages.Synchronization.Snapshot.getDefaultInstance()) return this;
        internalGetMutableCurrentOffsets().mergeFrom(
            other.internalGetCurrentOffsets());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Synchronization.Snapshot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Synchronization.Snapshot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Long> currentOffsets_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
      internalGetCurrentOffsets() {
        if (currentOffsets_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CurrentOffsetsDefaultEntryHolder.defaultEntry);
        }
        return currentOffsets_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
      internalGetMutableCurrentOffsets() {
        onChanged();;
        if (currentOffsets_ == null) {
          currentOffsets_ = com.google.protobuf.MapField.newMapField(
              CurrentOffsetsDefaultEntryHolder.defaultEntry);
        }
        if (!currentOffsets_.isMutable()) {
          currentOffsets_ = currentOffsets_.copy();
        }
        return currentOffsets_;
      }

      public int getCurrentOffsetsCount() {
        return internalGetCurrentOffsets().getMap().size();
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */

      @java.lang.Override
      public boolean containsCurrentOffsets(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetCurrentOffsets().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCurrentOffsetsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Long> getCurrentOffsets() {
        return getCurrentOffsetsMap();
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.Long> getCurrentOffsetsMap() {
        return internalGetCurrentOffsets().getMap();
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */
      @java.lang.Override

      public long getCurrentOffsetsOrDefault(
          java.lang.String key,
          long defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Long> map =
            internalGetCurrentOffsets().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */
      @java.lang.Override

      public long getCurrentOffsetsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Long> map =
            internalGetCurrentOffsets().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCurrentOffsets() {
        internalGetMutableCurrentOffsets().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */

      public Builder removeCurrentOffsets(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableCurrentOffsets().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Long>
      getMutableCurrentOffsets() {
        return internalGetMutableCurrentOffsets().getMutableMap();
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */
      public Builder putCurrentOffsets(
          java.lang.String key,
          long value) {
        if (key == null) { throw new NullPointerException("map key"); }
        
        internalGetMutableCurrentOffsets().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, uint64&gt; currentOffsets = 1;</code>
       */

      public Builder putAllCurrentOffsets(
          java.util.Map<java.lang.String, java.lang.Long> values) {
        internalGetMutableCurrentOffsets().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Snapshot)
    }

    // @@protoc_insertion_point(class_scope:Snapshot)
    private static final messages.Synchronization.Snapshot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.Synchronization.Snapshot();
    }

    public static messages.Synchronization.Snapshot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Snapshot>
        PARSER = new com.google.protobuf.AbstractParser<Snapshot>() {
      @java.lang.Override
      public Snapshot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Snapshot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Snapshot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.Synchronization.Snapshot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Snapshot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Snapshot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Snapshot_CurrentOffsetsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Snapshot_CurrentOffsetsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022protos/synch.proto\032\021protos/node.proto\"" +
      ")\n\013SyncRequest\022\032\n\004node\030\001 \001(\0132\014.NodeDetai" +
      "ls\"x\n\010Snapshot\0225\n\016currentOffsets\030\001 \003(\0132\035" +
      ".Snapshot.CurrentOffsetsEntry\0325\n\023Current" +
      "OffsetsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\004" +
      ":\0028\001B\033\n\010messagesB\017Synchronizationb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.Node.getDescriptor(),
        });
    internal_static_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncRequest_descriptor,
        new java.lang.String[] { "Node", });
    internal_static_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Snapshot_descriptor,
        new java.lang.String[] { "CurrentOffsets", });
    internal_static_Snapshot_CurrentOffsetsEntry_descriptor =
      internal_static_Snapshot_descriptor.getNestedTypes().get(0);
    internal_static_Snapshot_CurrentOffsetsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Snapshot_CurrentOffsetsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    messages.Node.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
